- name: check Rails installed
  shell: rails -v | cut -f 2 -d ' '
  register: rails_installed
  ignore_errors: yes
  tags:
    - ruby
    - ruby:install
    - install

- name: options single-request-reopen
  command: echo "options single-request-reopen" >> /etc/resolv.conf
  when: rails_installed.stdout != rails_version
  tags:
    - rails
    - install

- name: gem install rails -v {{ rails_version }} --no-ri --no-rdoc
  command: gem install rails -v {{ rails_version }} --no-ri --no-rdoc
  when: rails_installed.stdout != rails_version
  tags:
    - rails
    - install
